package com.example.mall.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   专题评论表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_topic_comment
 */
public class CmsTopicComment implements Serializable {
    private Long id;

    private String memberNickName;

    private Long topicId;

    private String memberIcon;

    private String content;

    private Date createTime;

    private Integer showStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.id
     *
     * @return the value of cms_topic_comment.id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.id
     *
     * @param id the value for cms_topic_comment.id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.member_nick_name
     *
     * @return the value of cms_topic_comment.member_nick_name
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public String getMemberNickName() {
        return memberNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.member_nick_name
     *
     * @param memberNickName the value for cms_topic_comment.member_nick_name
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setMemberNickName(String memberNickName) {
        this.memberNickName = memberNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.topic_id
     *
     * @return the value of cms_topic_comment.topic_id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.topic_id
     *
     * @param topicId the value for cms_topic_comment.topic_id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.member_icon
     *
     * @return the value of cms_topic_comment.member_icon
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public String getMemberIcon() {
        return memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.member_icon
     *
     * @param memberIcon the value for cms_topic_comment.member_icon
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setMemberIcon(String memberIcon) {
        this.memberIcon = memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.content
     *
     * @return the value of cms_topic_comment.content
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.content
     *
     * @param content the value for cms_topic_comment.content
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.create_time
     *
     * @return the value of cms_topic_comment.create_time
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.create_time
     *
     * @param createTime the value for cms_topic_comment.create_time
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.show_status
     *
     * @return the value of cms_topic_comment.show_status
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.show_status
     *
     * @param showStatus the value for cms_topic_comment.show_status
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberNickName=").append(memberNickName);
        sb.append(", topicId=").append(topicId);
        sb.append(", memberIcon=").append(memberIcon);
        sb.append(", content=").append(content);
        sb.append(", createTime=").append(createTime);
        sb.append(", showStatus=").append(showStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}