package com.example.mall.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   限时购通知记录
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_flash_promotion_log
 */
public class SmsFlashPromotionLog implements Serializable {
    private Integer id;

    private Integer memberId;

    private Long productId;

    private String memberPhone;

    private String productName;

    @ApiModelProperty(value = "会员订阅时间")
    private Date subscribeTime;

    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.id
     *
     * @return the value of sms_flash_promotion_log.id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.id
     *
     * @param id the value for sms_flash_promotion_log.id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.member_id
     *
     * @return the value of sms_flash_promotion_log.member_id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.member_id
     *
     * @param memberId the value for sms_flash_promotion_log.member_id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.product_id
     *
     * @return the value of sms_flash_promotion_log.product_id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.product_id
     *
     * @param productId the value for sms_flash_promotion_log.product_id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.member_phone
     *
     * @return the value of sms_flash_promotion_log.member_phone
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.member_phone
     *
     * @param memberPhone the value for sms_flash_promotion_log.member_phone
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.product_name
     *
     * @return the value of sms_flash_promotion_log.product_name
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.product_name
     *
     * @param productName the value for sms_flash_promotion_log.product_name
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.subscribe_time
     *
     * @return the value of sms_flash_promotion_log.subscribe_time
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Date getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.subscribe_time
     *
     * @param subscribeTime the value for sms_flash_promotion_log.subscribe_time
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setSubscribeTime(Date subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_flash_promotion_log.send_time
     *
     * @return the value of sms_flash_promotion_log.send_time
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_flash_promotion_log.send_time
     *
     * @param sendTime the value for sms_flash_promotion_log.send_time
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_flash_promotion_log
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", productId=").append(productId);
        sb.append(", memberPhone=").append(memberPhone);
        sb.append(", productName=").append(productName);
        sb.append(", subscribeTime=").append(subscribeTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}