package com.example.mall.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   会员积分成长规则表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ums_member_rule_setting
 */
public class UmsMemberRuleSetting implements Serializable {
    private Long id;

    @ApiModelProperty(value = "连续签到天数")
    private Integer continueSignDay;

    @ApiModelProperty(value = "连续签到赠送数量")
    private Integer continueSignPoint;

    @ApiModelProperty(value = "每消费多少元获取1个点")
    private BigDecimal consumePerPoint;

    @ApiModelProperty(value = "最低获取点数的订单金额")
    private BigDecimal lowOrderAmount;

    @ApiModelProperty(value = "每笔订单最高获取点数")
    private Integer maxPointPerOrder;

    @ApiModelProperty(value = "类型：0->积分规则；1->成长值规则")
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.id
     *
     * @return the value of ums_member_rule_setting.id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.id
     *
     * @param id the value for ums_member_rule_setting.id
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.continue_sign_day
     *
     * @return the value of ums_member_rule_setting.continue_sign_day
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Integer getContinueSignDay() {
        return continueSignDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.continue_sign_day
     *
     * @param continueSignDay the value for ums_member_rule_setting.continue_sign_day
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setContinueSignDay(Integer continueSignDay) {
        this.continueSignDay = continueSignDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.continue_sign_point
     *
     * @return the value of ums_member_rule_setting.continue_sign_point
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Integer getContinueSignPoint() {
        return continueSignPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.continue_sign_point
     *
     * @param continueSignPoint the value for ums_member_rule_setting.continue_sign_point
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setContinueSignPoint(Integer continueSignPoint) {
        this.continueSignPoint = continueSignPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.consume_per_point
     *
     * @return the value of ums_member_rule_setting.consume_per_point
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public BigDecimal getConsumePerPoint() {
        return consumePerPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.consume_per_point
     *
     * @param consumePerPoint the value for ums_member_rule_setting.consume_per_point
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setConsumePerPoint(BigDecimal consumePerPoint) {
        this.consumePerPoint = consumePerPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.low_order_amount
     *
     * @return the value of ums_member_rule_setting.low_order_amount
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public BigDecimal getLowOrderAmount() {
        return lowOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.low_order_amount
     *
     * @param lowOrderAmount the value for ums_member_rule_setting.low_order_amount
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setLowOrderAmount(BigDecimal lowOrderAmount) {
        this.lowOrderAmount = lowOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.max_point_per_order
     *
     * @return the value of ums_member_rule_setting.max_point_per_order
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Integer getMaxPointPerOrder() {
        return maxPointPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.max_point_per_order
     *
     * @param maxPointPerOrder the value for ums_member_rule_setting.max_point_per_order
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setMaxPointPerOrder(Integer maxPointPerOrder) {
        this.maxPointPerOrder = maxPointPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_rule_setting.type
     *
     * @return the value of ums_member_rule_setting.type
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_rule_setting.type
     *
     * @param type the value for ums_member_rule_setting.type
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", continueSignDay=").append(continueSignDay);
        sb.append(", continueSignPoint=").append(continueSignPoint);
        sb.append(", consumePerPoint=").append(consumePerPoint);
        sb.append(", lowOrderAmount=").append(lowOrderAmount);
        sb.append(", maxPointPerOrder=").append(maxPointPerOrder);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}