package com.example.mall.mapper;

import com.example.mall.model.PmsAlbum;
import com.example.mall.model.PmsAlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    long countByExample(PmsAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int deleteByExample(PmsAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int insert(PmsAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int insertSelective(PmsAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    List<PmsAlbum> selectByExample(PmsAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    PmsAlbum selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int updateByExampleSelective(@Param("record") PmsAlbum record, @Param("example") PmsAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int updateByExample(@Param("record") PmsAlbum record, @Param("example") PmsAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int updateByPrimaryKeySelective(PmsAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_album
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int updateByPrimaryKey(PmsAlbum record);
}