package com.example.mall.mapper;

import com.example.mall.model.UmsMemberRuleSetting;
import com.example.mall.model.UmsMemberRuleSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsMemberRuleSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    long countByExample(UmsMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int deleteByExample(UmsMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int insert(UmsMemberRuleSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int insertSelective(UmsMemberRuleSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    List<UmsMemberRuleSetting> selectByExample(UmsMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    UmsMemberRuleSetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int updateByExampleSelective(@Param("record") UmsMemberRuleSetting record, @Param("example") UmsMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int updateByExample(@Param("record") UmsMemberRuleSetting record, @Param("example") UmsMemberRuleSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int updateByPrimaryKeySelective(UmsMemberRuleSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Tue Sep 21 22:51:24 CST 2021
     */
    int updateByPrimaryKey(UmsMemberRuleSetting record);
}